SELECT DISTINCT "BRANDS", SUM("QUANTITY") AS TOTAL_CONSUMPTION
FROM BREWERY_DATA 
WHERE "COUNTRIES" IN ('Togo', 'Senegal', 'Benin') and "YEARS" IN (2017, 2018)
GROUP BY "BRANDS"
order by SUM("QUANTITY") DESC
LIMIT 3;


SELECT DISTINCT "BRANDS", SUM("QUANTITY") AS TOP_BRANDS
FROM BREWERY_DATA 
WHERE "COUNTRIES" = 'Ghana' 
GROUP BY "BRANDS"
ORDER BY SUM("QUANTITY")
LIMIT 1;


SELECT * FROM BREWERY_DATA;

SELECT DISTINCT "BRANDS", SUM("QUANTITY") TOTAL_QUANTITY, SUM("PROFIT") TOTAL_PROFIT,
SUM("UNIT_PRICE") TOTAL_UNIT_PRICE, SUM("COST") TOTAL_COST
FROM BREWERY_DATA
WHERE "COUNTRIES" = 'Nigeria'
GROUP BY "BRANDS";

SELECT DISTINCT "BRANDS"
FROM BREWERY_DATA;

SELECT * FROM BREWERY_DATA;

SELECT distinct "BRANDS", "YEARS", "COUNTRIES", SUM ("QUANTITY") TOTAL_QUANTITY
FROM BREWERY_DATA
WHERE 
"BRANDS" LIKE '%malt%' and "YEARS" BETWEEN 2018 AND 2019 AND "COUNTRIES" IN ('Nigeria', 'Ghana')
GROUP BY "BRANDS", "YEARS", "COUNTRIES"
ORDER BY "YEARS", SUM("QUANTITY");


SELECT DISTINCT "BRANDS", SUM("PROFIT") TOTAL_PROFIT, "YEARS"
FROM BREWERY_DATA
WHERE 
"YEARS" = 2019 AND "COUNTRIES" = 'Nigeria'
group by "BRANDS", "YEARS"
ORDER BY TOTAL_PROFIT DESC;


SELECT * FROM BREWERY_DATA;

SELECT DISTINCT("BRANDS"), SUM("QUANTITY") TOTAL_QTY, "REGION", "COUNTRIES"
FROM BREWERY_DATA
WHERE
"COUNTRIES" = 'Nigeria' and "REGION" = 'southsouth'
GROUP BY "REGION", "COUNTRIES", "BRANDS"
ORDER BY TOTAL_QTY DESC
LIMIT 1;

SELECT * FROM BREWERY_DATA;

SELECT  SUM("QUANTITY") QTY_CONSUMED
FROM BREWERY_DATA
WHERE "COUNTRIES" = 'Nigeria' AND "BRANDS" NOT LIKE ('%malt%');


select  "REGION", SUM("QUANTITY") BUDWEISER
FROM BREWERY_DATA
WHERE ( "COUNTRIES" = 'Nigeria' and "BRANDS" like ('%bud%'))
group by "REGION";


select  "REGION", SUM("QUANTITY") BUDWEISER
FROM BREWERY_DATA
WHERE ( "COUNTRIES" = 'Nigeria' and "BRANDS" like ('%bud%') AND "YEARS" = 2019)
group by "REGION";