select * from brewery_data;

SELECT "BRANDS", SUM("PROFIT") 
FROM BREWERY_DATA
WHERE "YEARS" IN (2017, 2018, 2019) AND "COUNTRIES" IN ('Nigeria', 'Togo', 'Senegal', 'Benin', 'Ghana')
GROUP BY "BRANDS";


SELECT "COUNTRIES" ANGLOPHONE_REGION, SUM("PROFIT") TOTAL_PROFIT
FROM BREWERY_DATA
WHERE "COUNTRIES"  IN ('Nigeria', 'Ghana')
group by ANGLOPHONE_REGION;

SELECT "COUNTRIES" FRANCOPHONE_REGION,  SUM("PROFIT") TOTAL_PROFIT
FROM BREWERY_DATA
WHERE "COUNTRIES" IN ('Togo', 'Senegal', 'Benin')
group by FRANCOPHONE_REGION;

select "COUNTRIES", SUM("PROFIT") TOTAL_PROFIT, "YEARS"
FROM BREWERY_DATA
WHERE "YEARS" = 2019
GROUP BY "COUNTRIES", "PROFIT", "YEARS"
ORDER BY TOTAL_PROFIT DESC
limit 1;



SELECT "YEARS", SUM("PROFIT") TOTAL_PROFIT
FROM BREWERY_DATA
GROUP BY "YEARS"
ORDER BY TOTAL_PROFIT DESC;

SELECT DISTINCT "COUNTRIES" FROM BREWERY_DATA;



SELECT "YEARS", "MONTHS", "PROFIT"
FROM BREWERY_DATA
ORDER BY "PROFIT"
LIMIT 1;

SELECT "PROFIT", "MONTHS", "YEARS"
FROM BREWERY_DATA
WHERE 
"MONTHS" = 'December' AND "YEARS" IN (2018)
ORDER BY "PROFIT"
LIMIT 1;


SELECT "MONTHS", (SUM("PROFIT") / SUM ("COST") * 100) AS PERCENTAGE_PROFIT
FROM BREWERY_DATA
WHERE "YEARS" = 2019
GROUP BY "MONTHS"
ORDER BY PERCENTAGE_PROFIT;

SELECT "COUNTRIES", "YEARS", "BRANDS", SUM("PROFIT") TOTAL_PROFIT
FROM BREWERY_DATA
WHERE
"COUNTRIES" = 'Senegal'
GROUP BY "COUNTRIES", "YEARS", "BRANDS"
ORDER BY TOTAL_PROFIT DESC
LIMIT 1;







