SELECT "COUNTRIES", SUM("QUANTITY") BEER_CONSUMPTION
FROM BREWERY_DATA
WHERE "BRANDS" NOT LIKE ('%MALT%')
GROUP BY "COUNTRIES"
ORDER BY BEER_CONSUMPTION DESC
LIMIT 1;

SELECT * FROM BREWERY_DATA;

SELECT "SALES_ID", "SALES_REP", "EMAILS", "PROFIT", "REGION", "YEARS"
FROM BREWERY_DATA
WHERE "COUNTRIES" = 'Senegal' and "BRANDS" LIKE ('%bud%')
GROUP BY "SALES_ID", "SALES_REP", "EMAILS", "REGION", "YEARS", "PROFIT"
ORDER BY "PROFIT" DESC
limit 1;

select "COUNTRIES", SUM("PROFIT") TOTAL_PROFIT
FROM BREWERY_DATA
WHERE "YEARS" = 2019 
AND "MONTHS" IN ('October', 'November', 'December')
group by "COUNTRIES"
ORDER BY TOTAL_PROFIT DESC
LIMIT 1;